#############################################################################
# Release settings
#############################################################################
release:
  #############################################################################
  # Generated image settings
  #############################################################################
  # Base image for the pre-release image
  base_tag: ubuntu:22.04
  # Build platforms for the pre-release and final images
  build_platforms:
  - linux/amd64
  - linux/arm64
  # Push pre-release image to GitHub for testing
  prerelease_tag: ghcr.io/mentalsmash/ref-project-debdocker-test
  # Image tag for the final release image.
  # Published to both GitHub and DockerHub
  release_tags:
  - ghcr.io/mentalsmash/ref-project-debdocker
  - mentalsmash/ref-project-debdocker
  # Add an arbitrary suffix to the image tags
  tag_suffix: ''
  #############################################################################
  # Release badges settings
  #############################################################################
  # Gist IDs for the JSON objects backing release badges
  badges:
    nightly:
      base_image: "1fd45f442b8ab91bef6ef56423368128"
      version:    "9653c15d4e5b0413fb71397e643ab822"
    stable:
      base_image: "6391e3a762e26c822281b1dbf2af5bd1"
      version:    "2fda06b2047d0643d91308462197110a"

#############################################################################
# Pull Request settings
#############################################################################
pull_request:
  validation:
    basic:
      platforms:
      - amd64
      base_images:
      - ubuntu:22.04
    full:
      platforms:
      - arm64
      base_images:
      - ubuntu:22.04

#############################################################################
# CI infrastructure settings
#############################################################################
ci:
  # Docker image with administration tools
  admin_image: ghcr.io/${{ github.repository }}-admin:latest

debian:
  base_images:
  - ubuntu:22.04
  platforms:
  - amd64
  - arm64
  artifacts_prefix: mentalsmash-ref-project-debdocker-deb-
