###############################################################################
# Copyright 2020-2024 Andrea Sorbini
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
from typing import NamedTuple


def configure(cfg: NamedTuple, github: NamedTuple, inputs: NamedTuple) -> dict:
  # A prefix for files generated by the test
  test_id = f"release-{cfg.dyn.build.label}__{cfg.dyn.build.version}"
  # Name for the artifact generated by the test
  test_artifact = f"{github.repository.replace('/', '-')}-test-{test_id}__{cfg.dyn.test_date}"
  return {
    "TEST_ID": test_id,
    "TEST_ARTIFACT": test_artifact,
  }
