name: Release Step (Build Image)
run-name: |
  release (build) [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

on:
  workflow_call:

  workflow_dispatch:

concurrency:
  group: release-${{github.ref}}-build

permissions:
  contents: read
  packages: write

env:
  CLONE_DIR: src/repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Configure workflow
        id: config
        shell: python
        run: |
          import sys
          sys.path.insert(0, "${{ env.CLONE_DIR }}/.github")
          from workflows_pyconfig import configure
          configure(
            github="""${{ toJson(github) }}""",
            outputs="""\
              DOCKER_BASE_IMAGE = cfg.release.base_image
              DOCKER_TAGS_CONFIG = cfg.dyn.docker.tags_config
              DOCKER_FLAVOR_CONFIG = cfg.dyn.docker.flavor_config
              DOCKER_BUILD_PLATFORMS = cfg.dyn.docker.build_platforms
              LOGIN_DOCKERHUB = cfg.dyn.prerelease.login_dockerhub
              LOGIN_GITHUB = cfg.dyn.prerelease.login_github
              PRERELEASE_REPO = cfg.release.prerelease_repo
            """)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.config.outputs.PRERELEASE_REPO }}
          tags: ${{ steps.config.outputs.DOCKER_TAGS_CONFIG }}
          flavor: ${{ steps.config.outputs.DOCKER_FLAVOR_CONFIG }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Log in to GitHub
        if: steps.config.outputs.LOGIN_GITHUB
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to Docker HUb
        if: steps.config.outputs.LOGIN_DOCKERHUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push test images
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.CLONE_DIR }}/docker/Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          push: true
          context: ${{ env.CLONE_DIR }}
          platforms: ${{ steps.config.outputs.DOCKER_BUILD_PLATFORMS }}
          build-args: |
            BASE_IMAGE=${{ steps.config.outputs.DOCKER_BASE_IMAGE }}
