name: Release Step (Push Image)
run-name: |
  release (push [${{github.ref_type == 'branch' && 'nightly' || 'stable'}} image, ${{github.ref_name}}]

on:
  workflow_call:
    inputs:
      docker-flavor-config:
        type: string
        required: true
      docker-tags-config:
        type: string
        required: true
      release-tags:
        type: string
        required: true
      release-tag-platforms:
        type: string
        required: true
      test-tag:
        type: string
        required: true
      test-tag-registry:
        type: string
        required: true

concurrency:
  group: release-${{github.ref_type == 'branch' && 'nightly' || 'stable'}}-${{ github.ref }}-push-images

env:
  CLONE_DIR: src/repo
  DOCKERFILE: docker/release/Dockerfile

permissions:
  contents: read
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Configure push
        id: config
        shell: python
        run: |
          import sys
          sys.path.insert(0, "${{ env.CLONE_DIR }}/scripts")
          from action_helpers.workflows.release_push import configure

          configure(
            release_tags="""\
              ${{inputs.release-tags}}
            """,
            test_tag_registry="${{inputs.test-tag-registry}}",
          )

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Extract image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.release-tags }}
          tags: ${{ inputs.docker-tags-config }}
          flavor: ${{ inputs.docker-flavor-config }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ steps.config.outputs.LOGIN_DOCKERHUB }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Log in to GitHub
        uses: docker/login-action@v3
        if: ${{ steps.config.outputs.LOGIN_GITHUB }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build and push images to GitHub
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.CLONE_DIR }}/${{ env.DOCKERFILE }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          push: true
          context: ${{ env.CLONE_DIR }}
          platforms: ${{ inputs.release-tag-platforms }}
          build-args: |
            BASE_IMAGE=${{ inputs.test-tag }}
