name: Release Step (Push Image)
run-name: |
  release (push [${{github.ref_type == 'branch' && 'nightly' || 'stable'}} image, ${{github.ref_name}}]

on:
  workflow_call:

  workflow_dispatch:

concurrency:
  group: release-${{github.ref_type == 'branch' && 'nightly' || 'stable'}}-${{ github.ref }}-push-images

env:
  CLONE_DIR: src/repo

permissions:
  contents: read
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true
      
      - name: Load configuration
        uses: mentalsmash/actions/pyconfig/configuration@master
        with:
          clone-dir: ${{ env.CLONE_DIR }}

      - name: Configure workflow
        id: config
        run: 
          (
            echo DOCKER_BUILD_PLATFORMS=$(jq '.release.build_platforms_config' -j pyconfig.json)
            echo "DOCKER_FLAVOR_CONFIG<<EOF"
            jq '.release.flavor_config' -j pyconfig.json
            echo EOF
            echo "DOCKER_TAGS_CONFIG<<EOF"
            jq '.release.tags_config' -j pyconfig.json
            echo EOF
            echo LOGIN_DOCKERHUB=$(jq '.release.login.dockerhub' -j pyconfig.json)
            echo LOGIN_GITHUB=$(jq '.release.login.github' -j pyconfig.json)
            echo PRERELEASE_IMAGE=$(jq '.release.prerelease_image' -j pyconfig.json)
            echo RELEASE_REPOS=$(jq '.release.final_repos_config' -j pyconfig.json)
          ) >> ${GITHUB_OUTPUT}
      
      - name: Build image
        uses: mentalsmash/actions/docker/builder@master
        with:
          base-image: ${{ steps.config.outputs.PRERELEASE_IMAGE }}
          build-platforms: ${{ steps.config.outputs.DOCKER_BUILD_PLATFORMS }}
          dockerfile: ${{ env.CLONE_DIR }}/docker/release/Dockerfile
          context: ${{ env.CLONE_DIR }}
          image-repos: ${{ steps.config.outputs.RELEASE_REPOS }}
          image-flavor-config: ${{ steps.config.outputs.DOCKER_FLAVOR_CONFIG }}
          image-tags-config: ${{ steps.config.outputs.DOCKER_TAGS_CONFIG }}
          github-token: ${{ steps.config.outputs.LOGIN_GITHUB && secrets.GITHUB_TOKEN || '' }}
          github-user: ${{ steps.config.outputs.LOGIN_GITHUB && github.actor || '' }}
          dockerhub-token: ${{ steps.config.outputs.LOGIN_DOCKERHUB && secrets.DOCKERHUB_TOKEN || '' }}
          dockerhub-user: ${{ steps.config.outputs.LOGIN_DOCKERHUB && secrets.DOCKERHUB_USERNAME || '' }}
          action: push

