name: Release Step (Update Badges)
run-name: |
  release (update badges) [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

concurrency:
  group: release-${{github.ref_type == 'branch' && 'nightly' || 'stable'}}-${{github.ref}}-update-badges

on:
  workflow_call:
    inputs:
      base-image:
        type: string
        required: true
      badge-version:
        type: string
      badge-base-img:
        type: string

env:
  CLONE_DIR: src/repo

jobs:
  update_badges:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source repository
      uses: actions/checkout@v4
      with:
        path: ${{ env.CLONE_DIR }}
        submodules: true

    - name: Generate badge configuration
      id: config
      shell: python
      run: |
        import sys
        sys.path.insert(0, "${{ env.CLONE_DIR }}/scripts")
        from action_helpers.workflows.release_badges import configure

        configure(
          clone_dir="${{env.CLONE_DIR}}",
          ref_type="${{github.ref_type}}",
          ref_name="${{github.ref_name}}",
          repository="${{github.repository}}")

    - name: Update version badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE_TOKEN }}
        gistID: ${{ inputs.badge-version }}
        filename: ${{ steps.config.outputs.BADGE_FILENAME }}-version.json
        label: version
        message: ${{ steps.config.outputs.VERSION }}
        color: ${{ steps.config.outputs.COLOR_VERSION }}

    - name: Update base image badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE_TOKEN }}
        gistID: ${{ inputs.badge-base-img }}
        filename: ${{ steps.config.outputs.BADGE_FILENAME }}-base-img.json
        label: base image
        message: ${{ inputs.base-image }}
        color: ${{ steps.config.outputs.COLOR_BASE_IMG }}
