name: Release Step (Summary)
run-name: |
  release (Summary) [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

concurrency:
  group: release-${{github.ref_type == 'branch' && 'nightly' || 'stable'}}-${{github.ref}}-summary

on:
  workflow_call:

  workflow_dispatch:

env:
  CLONE_DIR: src/repo

jobs:
  update_badges:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source repository
      uses: actions/checkout@v4
      with:
        path: ${{ env.CLONE_DIR }}
        submodules: true

    - name: Configure workflow
      id: config
      shell: python
      run: |
        import sys
        sys.path.insert(0, "${{ env.CLONE_DIR }}/.github")
        from workflows_pyconfig import configure
        configure(
          github="""${{ toJson(github) }}""",
          outputs="""\
            BADGE_BASE_IMAGE_COLOR = cfg.dyn.badge.base_image.color
            BADGE_BASE_IMAGE_FILENAME = cfg.dyn.badge.base_image.filename
            BADGE_BASE_IMAGE_GIST = cfg.dyn.badge.base_image.gist
            BADGE_BASE_IMAGE_MESSAGE = cfg.dyn.badge.base_image.message
            BADGE_VERSION_COLOR = cfg.dyn.badge.version.color
            BADGE_VERSION_FILENAME = cfg.dyn.badge.version.filename
            BADGE_VERSION_GIST = cfg.dyn.badge.version.gist
            BADGE_VERSION_MESSAGE = cfg.dyn.badge.version.message
          """)
        

    - name: Update version badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        label: version
        auth: ${{ secrets.GIST_UPDATE_TOKEN }}
        color: ${{ steps.config.outputs.BADGE_VERSION_COLOR }}
        filename: ${{ steps.config.outputs.BADGE_VERSION_FILENAME }}
        gistID: ${{ steps.config.outputs.BADGE_VERSION_GIST }}
        message: ${{ steps.config.outputs.BADGE_VERSION_MESSAGE }}

    - name: Update base image badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        label: base image
        auth: ${{ secrets.GIST_UPDATE_TOKEN }}
        color: ${{ steps.config.outputs.BADGE_BASE_COLOR }}
        filename: ${{ steps.config.outputs.BADGE_BASE_IMAGE_FILENAME }}
        gistID: ${{ steps.config.outputs.BADGE_BASE_IMAGE }}
        message: ${{ steps.config.outputs.BADGE_BASE_IMAGE_MESSGE }}
