name: Setup CI
run-name: periodic infrastructure setup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1 1 * *"

concurrency:
  group: ci-setup
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  build-image-debian-builder:
    uses: ./.github/workflows/image_build_debian_builder.yml
    secrets: inherit

  build-image-ci-tester:
    uses: ./.github/workflows/image_build_tester.yml
    secrets: inherit

  build-image-admin:
    uses: ./.github/workflows/image_build_admin.yml
    secrets: inherit
