name: Deb Release
run-name: |
  deb release [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  workflow_call:

concurrency:
  group: deb-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

env:
  CLONE_DIR: src/repo

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      DEB_ENABLED: ${{steps.config.outputs.DEB_ENABLED}}
      DEB_BASE_IMAGES_MATRIX: ${{steps.config.outputs.DEB_BASE_IMAGES_MATRIX}}
      DEB_BUILD_ARCHITECTURES_MATRIX: ${{steps.config.outputs.DEB_BUILD_ARCHITECTURES_MATRIX}}
      DEB_ARTIFACTS_PREFIX: ${{steps.config.outputs.DEB_ARTIFACTS_PREFIX}}
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Configure workflow
        id: config
        shell: python
        run: |
          import sys
          sys.path.insert(0, "${{ env.CLONE_DIR }}/.github")
          from workflows_pyconfig import configure
          configure(
            github="""${{ toJson(github) }}""",
            outputs="""\
              DEB_BASE_IMAGES_MATRIX = cfg.debian.builder.base_images_matrix
              DEB_BUILD_ARCHITECTURES_MATRIX = cfg.debian.builder.architectures_matrix
              DEB_ARTIFACTS_PREFIX = cfg.debian.artifacts.prefix
              DEB_ENABLED = cfg.debian.enabled
            """)

  build-packages:
    needs: config
    if: needs.config.outputs.DEB_ENABLED
    strategy:
      matrix:
        base-image: ${{ fromJson(needs.config.outputs.DEB_BASE_IMAGES_MATRIX ) }}
        build-architecture: ${{ fromJson(needs.config.outputs.DEB_BUILD_ARCHITECTURES_MATRIX) }}
    uses: ./.github/workflows/_deb_build.yml
    secrets: inherit
    with:
      base-image: ${{ matrix.base-image }}
      build-architecture: ${{ matrix.build-architecture }}

  publish_release:
    needs:
      - build-packages
      - config
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ needs.config.outputs.DEB_ARTIFACTS_PREFIX }}*
        path: ${{ github.workspace }}/artifacts
        merge-multiple: true

    - name: Create new release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/*.deb
