name: Docker Build (Periodic Trigger)
run-name: docker build [periodic trigger]

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1 1 * *"

concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  build-image-ci-tester:
    uses: ./.github/workflows/docker_build_tester.yml
    secrets: inherit
