name: Image Build (tester)
run-name: |
  docker build [tester]

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - master
    paths:
      - docker/tester/**
      - .github/workflows/image_build_tester.yml
      - .github/workflows/image_builder.yml

concurrency:
  group: image-build-tester
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

env:
  CLONE_DIR: src/repo

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      CLONE_DIR: ${{ steps.config.outputs.CLONE_DIR }}
      TESTER_IMAGE_BASE_IMAGE_MATRIX: ${{ steps.config.outputs.TESTER_IMAGE_BASE_IMAGE_MATRIX }}
      TESTER_IMAGE_BUILD_PLATFORMS: ${{ steps.config.outputs.TESTER_IMAGE_BUILD_PLATFORMS }}
      TESTER_IMAGE_REPO: ${{ steps.config.outputs.TESTER_IMAGE_REPO }}
      LOGIN_DOCKERHUB: ${{ steps.config.outputs.LOGIN_DOCKERHUB }}
      LOGIN_GITHUB: ${{ steps.config.outputs.LOGIN_GITHUB }}
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true
      
      - name: Configure workflow
        id: config
        shell: python
        run: |
          import sys
          sys.path.insert(0, "${{ env.CLONE_DIR }}/.github")
          from workflows_pyconfig import configure
          configure(
            github="""${{ toJson(github) }}""",
            outputs="""\
              CLONE_DIR = cfg.build.clone_dir
              TESTER_IMAGE_REPO = cfg.ci.images.tester.repo
              TESTER_IMAGE_BUILD_PLATFORMS = cfg.ci.images.tester.build_platforms_config
              TESTER_IMAGE_BASE_IMAGE_MATRIX = cfg.ci.images.tester.base_image_matrix
              LOGIN_GITHUB = cfg.ci.images.tester.login.github
              LOGIN_DOCKERHUB = cfg.ci.images.tester.login.dockerhub
            """)

  build:
    needs:
      - config
    strategy:
      matrix:
        base-image: ${{ fromJson(needs.config.outputs.TESTER_IMAGE_BASE_IMAGE_MATRIX) }}
    uses: ./.github/workflows/image_builder.yml
    with:
      base-image: ${{ matrix.base-image }}
      build-platforms: ${{ needs.config.outputs.TESTER_IMAGE_BUILD_PLATFORMS }}
      dockerfile: ${{ needs.config.outputs.CLONE_DIR }}/docker/tester/Dockerfile
      image-repos: ${{ needs.config.outputs.TESTER_IMAGE_REPO }}
      login-dockerhub: ${{ needs.config.outputs.LOGIN_DOCKERHUB && true || false }}
      login-github: ${{ needs.config.outputs.LOGIN_GITHUB && true || false }}
      push: true
