name: Image Build (debian-builder)
run-name: |
  docker build [ghcr.io/${{ github.repository }}-debian-builder]

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - master
    paths:
      - docker/debian-builder/**
      - .github/workflows/image_build_debian_builder.yml

concurrency:
  group: uno-ci-image-build-debian-builder
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        base-image: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4

      - name: Generate build config
        id: config
        run: |
          image_tag=$(echo "${{matrix.base-image}}" | tr : -)
          (
            echo IMAGE_TAG=${image_tag}
          ) >> ${GITHUB_OUTPUT}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: meta-docker
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-debian-builder
          tags: ${{ steps.config.outputs.IMAGE_TAG }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Log in to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push debian builder image
        uses: docker/build-push-action@v5
        with:
          file: docker/debian-builder/Dockerfile
          tags: ${{ steps.meta-docker.outputs.tags }}
          annotations: ${{ steps.meta-docker.outputs.annotations }}
          labels: ${{ steps.meta-docker.outputs.labels }}
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
