name: Image Build (admin)
run-name: |
  docker build [admin]

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - master
    paths:
      - docker/admin/**
      - .github/workflows/image_build_admin.yml

concurrency:
  group: image-build-admin
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

env:
  CLONE_DIR: src/repo

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      ADMIN_IMAGE_BASE_IMAGE: ${{ steps.config.outputs.ADMIN_IMAGE_BASE_IMAGE }}
      ADMIN_IMAGE_BUILD_PLATFORMS: ${{ steps.config.outputs.ADMIN_IMAGE_BUILD_PLATFORMS }}
      ADMIN_IMAGE_REPO: ${{ steps.config.outputs.ADMIN_IMAGE_REPO }}
      ADMIN_IMAGE_TAGS_CONFIG: ${{ steps.config.outputs.ADMIN_IMAGE_TAGS_CONFIG }}
      CLONE_DIR: ${{ steps.config.outputs.CLONE_DIR }}
      LOGIN_DOCKERHUB: ${{ steps.config.outputs.LOGIN_DOCKERHUB }}
      LOGIN_GITHUB: ${{ steps.config.outputs.LOGIN_GITHUB }}
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true
      
      - name: Configure workflow
        id: config
        shell: python
        run: |
          import sys
          sys.path.insert(0, "${{ env.CLONE_DIR }}/.github")
          from workflows_pyconfig import configure
          configure(
            github="""${{ toJson(github) }}""",
            outputs="""\
              ADMIN_IMAGE_REPO = cfg.ci.images.admin.repo
              ADMIN_IMAGE_TAGS_CONFIG = cfg.ci.images.admin.tags_config
              ADMIN_IMAGE_BASE_IMAGE = cfg.ci.images.admin.base_image
              ADMIN_IMAGE_BUILD_PLATFORMS = cfg.ci.images.admin.build_platforms_config
              LOGIN_DOCKERHUB = cfg.ci.images.admin.login.dockerhub
              LOGIN_GITHUB = cfg.ci.images.admin.login.github
              CLONE_DIR = cfg.build.clone_dir
            """)

  build:
    needs: config
    uses: ./.github/workflows/image_builder.yml
    with:
      base-image: ${{ needs.config.outputs.ADMIN_IMAGE_BASE_IMAGE }}
      build-platforms: ${{ needs.config.outputs.ADMIN_IMAGE_BUILD_PLATFORMS }}
      dockerfile: ${{ needs.config.outputs.CLONE_DIR }}/docker/admin/Dockerfile
      image-repos: ${{ needs.config.outputs.ADMIN_IMAGE_REPO }}
      image-tags-config: ${{ needs.config.outputs.ADMIN_IMAGE_TAGS_CONFIG }}
      login-github: ${{ needs.config.outputs.LOGIN_GITHUB && true || false }}
      login-dockerhub: ${{ needs.config.outputs.LOGIN_DOCKERHUB && true || false }}
      push: true

