name: Pull Request (Closed)
run-name: |
  PR #${{github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number}} [closed, ${{ ((github.event_name == 'pull_request' && github.event.pull_request.merged) || inputs.pr-merged) && 'merged' || 'rejected' }}${{ github.event_name != 'pull_request' && ', manual trigger' || '' }}] ${{github.event_name == 'pull_request' && github.event.pull_request.title || ''}}

on:
  pull_request:
    types:
      - closed
    # Matching triggers with pull_request.yml
    paths-ignore:
      - 'README.md'
      - 'docs/**/*'
    branches:
      - master
  workflow_dispatch:
    inputs:
      pr-number:
        description: "PR #"
        type: number
        required: true
      pr-merged:
        description: "Merged"
        type: boolean
        default: true

concurrency:
  group: pr-closed-${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number }}
  cancel-in-progress: false

permissions:
  actions: write
  packages: read

env:
  CLONE_DIR: src/repo

jobs:
  cleanup_jobs:
    runs-on: ubuntu-latest
    # Run automatically only if the PR is from this repository,
    # otherwise it won't be authorized to delete workflow runs.
    # (suggested by https://github.com/orgs/community/discussions/25217)
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Load configuration
        uses: mentalsmash/actions/pyconfig/configuration@master
        with:
          clone-dir: ${{ env.CLONE_DIR }}
  
      - name: Configure workflow
        id: config
        run: |
          (
            echo ADMIN_IMAGE=$(jq '.ci.images.admin.image' -r pyconfig.json)
            echo LOGIN_DOCKERHUB=$(jq '.ci.images.admin.login.dockerhub' -r pyconfig.json)
            echo LOGIN_GITHUB=$(jq '.ci.images.admin.login.github' -r pyconfig.json)
          ) | tee -a ${GITHUB_OUTPUT}

      - name: "Clean up workflow runs for PR"
        uses: mentalsmash/actions/ci/admin@master
        with:
          image: ${{ steps.config.outputs.ADMIN_IMAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ steps.config.outputs.LOGIN_GITHUB && secrets.GITHUB_TOKEN || '' }}
          github-user: ${{ steps.config.outputs.LOGIN_GITHUB && github.actor || '' }}
          dockerhub-token: ${{ steps.config.outputs.LOGIN_DOCKERHUB && secrets.DOCKERHUB_TOKEN || '' }}
          dockerhub-user: ${{ steps.config.outputs.LOGIN_DOCKERHUB && secrets.DOCKERHUB_USERNAME || '' }}
          args: |
            -c
            ${{ github.run_id }}
            pr-closed
            -r
            ${{ github.repository }}
            -N
            ${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number }}
            ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged || inputs.pr-merged) && '-m' || '' }}

