name: Release
run-name: |
  release [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: release-${{github.ref_type == 'tag' && 'stable' || 'nightly' }}
  cancel-in-progress: false

permissions:
  actions:  write
  contents: write
  packages: write

jobs:
  cleanup-prerelease:
    uses: ./.github/workflows/release_cleanup_prerelease.yml
    secrets: inherit

  release-docker:
    needs:
    - cleanup-prerelease
    uses: ./.github/workflows/release_docker.yml
    secrets: inherit
  
  release-deb:
    uses: ./.github/workflows/release_deb.yml
    secrets: inherit
  
  summary:
    needs:
      - release-docker
      - release-deb
    uses: ./.github/workflows/release_summary.yml
    secrets: inherit

  cleanup-jobs:
    needs:
      - release-docker
      - release-deb
    uses: ./.github/workflows/release_cleanup_jobs.yml
    secrets: inherit

  cleanup-tracker:
    needs:
      - release-docker
      - release-deb
    uses: ./.github/workflows/release_cleanup_tracker.yml
    secrets: inherit
