name: Release
run-name: |
  release [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release-docker:
    uses: ./.github/workflows/release_deb.yml
    secrets: inherit
  
  release-deb:
    uses: ./.github/workflows/release_docker.yml
    secrets: inherit

  summary:
    needs:
      - release-docker
      - release-deb
    uses: ./.github/workflows/release_summary.yml
    secrets: inherit
