name: Release
run-name: |
  release [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

env:
  CLONE_DIR: src/repo

jobs:
  build:
    uses: ./.github/workflows/_release_build.yml
    secrets: inherit

  deb_release:
    uses: ./.github/workflows/deb_release.yml
    secrets: inherit

  test:
    needs:
      - build
    uses: ./.github/workflows/_release_test.yml
    secrets: inherit

  push:
    needs:
      - test
    uses: ./.github/workflows/_release_push.yml
    secrets: inherit

  update_badges:
    needs:
      - push
    uses: ./.github/workflows/_release_badges.yml
    secrets: inherit

  summarize:
    needs:
      - deb_release
      - push
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Configure and summarize workflow
        id: config
        shell: python
        run: |
          import sys
          sys.path.insert(0, "${{ env.CLONE_DIR }}/.github")
          from workflows_pyconfig import summarize
          summarize(workflow="release", github="""${{ toJson(github) }}""")
