name: Release (Docker Images)
run-name: |
  docker release [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  workflow_call:

concurrency:
  group: docker-release-${{github.ref_type == 'tag' && 'stable' || 'nightly' }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

env:
  CLONE_DIR: src/repo

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      ADMIN_IMAGE: ${{ steps.config.outputs.ADMIN_IMAGE }}
      BUILD_PROFILE: ${{ steps.config.outputs.BUILD_PROFILE }}
      BUILD_VERSION: ${{ steps.config.outputs.BUILD_VERSION }}
      DOCKER_BASE_IMAGE: ${{ steps.config.outputs.DOCKER_BASE_IMAGE }}
      DOCKER_BUILD_PLATFORMS: ${{ steps.config.outputs.DOCKER_BUILD_PLATFORMS }}
      DOCKER_FLAVOR_CONFIG: ${{ steps.config.outputs.DOCKER_FLAVOR_CONFIG }}
      DOCKER_TAGS_CONFIG: ${{ steps.config.outputs.DOCKER_TAGS_CONFIG }}
      LOCAL_TESTER_IMAGE: ${{ steps.config.outputs.LOCAL_TESTER_IMAGE }}
      LOCAL_TESTER_RESULTS: ${{ steps.config.outputs.LOCAL_TESTER_RESULTS }}
      PRERELEASE_PACKAGE: ${{ steps.config.outputs.PRERELEASE_PACKAGE }}
      PRERELEASE_PACKAGE_ORG: ${{ steps.config.outputs.PRERELEASE_PACKAGE_ORG }}
      PRERELEASE_REPO: ${{ steps.config.outputs.PRERELEASE_REPO }}
      PRERELEASE_IMAGE: ${{ steps.config.outputs.PRERELEASE_IMAGE }}
      RELEASE_FINAL_IMAGES: ${{ steps.config.outputs.RELEASE_FINAL_IMAGES }}
      RELEASE_REPOS: ${{ steps.config.outputs.RELEASE_REPOS }}
      TEST_ARTIFACT: ${{ steps.config.outputs.TEST_ARTIFACT }}
      TEST_DATE: ${{ steps.config.outputs.TEST_DATE }}
      TEST_ID: ${{ steps.config.outputs.TEST_ID }}
      TEST_RUNNERS_MATRIX: ${{ steps.config.outputs.TEST_RUNNERS_MATRIX }}
      TRACKER_USER_NAME: ${{ steps.config.outputs.TRACKER_USER_NAME }}
      TRACKER_USER_EMAIL: ${{ steps.config.outputs.TRACKER_USER_EMAIL }}
      TRACKER_REPO: ${{ steps.config.outputs.TRACKER_REPO }}
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Load configuration
        uses: mentalsmash/actions/pyconfig/configuration@master
        with:
          clone-dir: ${{ env.CLONE_DIR }}

      - name: Configure workflow
        id: config
        run: |
          (
            printf -- "ADMIN_IMAGE=%s\n" "$(jq '.ci.images.admin.image' -r pyconfig.json)"
            printf -- "BUILD_PROFILE=%s\n" "$(jq '.build.profile' -r pyconfig.json)"
            printf -- "BUILD_SETTINGS_ARTIFACT=%s\n" "$(jq '.build.settings.artifact' -j pyconfig.json)"
            printf -- "BUILD_VERSION=%s\n" "$(jq '.build.version' -r pyconfig.json)"
            printf -- "DOCKER_BASE_IMAGE=%s\n" "$(jq '.release.base_image' -j pyconfig.json)"
            printf -- "%s\n" "DOCKER_TAGS_CONFIG<<EOF"
            # printf -- "%s\n" "$(jq '.release.tags_config' -j pyconfig.json)"
            jq '.release.tags_config' -j pyconfig.json
            echo
            printf -- "%s\n" EOF
            printf -- "%s\n" "DOCKER_FLAVOR_CONFIG<<EOF"
            # printf -- "%s\n" "$(jq '.release.flavor_config' -j pyconfig.json)"
            jq '.release.flavor_config' -j pyconfig.json
            echo
            printf -- "%s\n" EOF
            printf -- "DOCKER_BUILD_PLATFORMS=%s\n" "$(jq '.release.build_platforms_config' -j pyconfig.json)"
            printf -- "LOCAL_TESTER_IMAGE=%s\n" "$(jq '.ci.images.local_tester.image' -j pyconfig.json)"
            printf -- "LOCAL_TESTER_RESULTS=%s\n" "$(jq '.ci.test.results_dir' -j pyconfig.json)"
            printf -- "PRERELEASE_PACKAGE=%s\n" "$(jq '.release.prerelease_package' -j pyconfig.json)"
            printf -- "PRERELEASE_PACKAGE_ORG=%s\n" "$(jq '.release.prerelease_package_org' -j pyconfig.json)"
            printf -- "PRERELEASE_REPO=%s\n" "$(jq '.release.prerelease_repo' -j pyconfig.json)"
            printf -- "PRERELEASE_IMAGE=%s\n" "$(jq '.release.prerelease_image' -j pyconfig.json)"
            printf -- "%s\n" "RELEASE_REPOS<<EOF"
            # printf -- "%s\n" "$(jq '.release.final_repos_config' -j pyconfig.json)"
            jq '.release.final_repos_config' -j pyconfig.json
            echo
            printf -- "%s\n" EOF
            echo "RELEASE_FINAL_IMAGES<<EOF"
            # printf -- "%s\n" "$(jq '.release.final_images' -r pyconfig.json)"
            jq '.release.final_images' -r pyconfig.json
            echo
            echo EOF
            printf -- "TEST_ARTIFACT=%s\n" "$(jq '.release.test_artifact' -j pyconfig.json)"
            printf -- "TEST_DATE=%s\n" "$(jq '.build.date' -j pyconfig.json)"
            printf -- "TEST_ID=%s\n" "$(jq '.release.test_id' -j pyconfig.json)"
            printf -- "TEST_RUNNERS_MATRIX=%s\n" "$(jq '.release.test_runners_matrix' -j pyconfig.json)"
            printf -- "TRACKER_USER_NAME=%s\n" "$(jq '.release.tracker.user.name' -r pyconfig.json)"
            printf -- "TRACKER_USER_EMAIL=%s\n" "$(jq '.release.tracker.user.email' -r pyconfig.json)"
            printf -- "TRACKER_REPO=%s\n" "$(jq '.release.tracker.repository' -r pyconfig.json)"
          ) | tee -a ${GITHUB_OUTPUT}

      - name: Upload project settings
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.config.outputs.BUILD_SETTINGS_ARTIFACT }}
          path: pyconfig.json

  build:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Delete all versions of the prerelease package
        if: needs.config.outputs.PRERELEASE_PACKAGE
        uses: mentalsmash/actions/ci/admin@master
        with:
          image: ${{ needs.config.outputs.ADMIN_IMAGE }}
          token: ${{ secrets.PACKAGE_VERSIONS_PAT }}
          args: |
            -c
            ${{ github.run_id }}
            delete-versions
            -o
            ${{ needs.config.outputs.PRERELEASE_PACKAGE_ORG }}
            -p
            ${{ needs.config.outputs.PRERELEASE_PACKAGE }}
            --if-package-exists

      - name: Build image
        uses: mentalsmash/actions/docker/builder@master
        with:
          base-image: ${{ needs.config.outputs.DOCKER_BASE_IMAGE }}
          build-platforms: ${{ needs.config.outputs.DOCKER_BUILD_PLATFORMS }}
          context: ${{ env.CLONE_DIR }}
          dockerfile: ${{ env.CLONE_DIR }}/docker/Dockerfile
          image-flavor-config: ${{ needs.config.outputs.DOCKER_FLAVOR_CONFIG }}
          image-tags-config: ${{ needs.config.outputs.DOCKER_TAGS_CONFIG }}
          image-repos: ${{ needs.config.outputs.PRERELEASE_REPO }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-user: ${{ github.actor }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          action: push

  test:
    needs:
      - config
      - build
    strategy:
      matrix:
        runner: ${{ fromJson(needs.config.outputs.TEST_RUNNERS_MATRIX) }} 
    runs-on: ${{ fromJson(matrix.runner) }}
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true
      
      - name: Build image
        uses: mentalsmash/actions/docker/builder@master
        with:
          base-image: ${{ needs.config.outputs.PRERELEASE_IMAGE }}
          dockerfile: ${{ env.CLONE_DIR }}/docker/test/Dockerfile
          context: ${{ env.CLONE_DIR }}
          image-tags: ${{ needs.config.outputs.LOCAL_TESTER_IMAGE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-user: ${{ github.actor }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          action: load

      - name: Generate architecture ID
        id: arch
        run: |
          (
            case "$(uname -m)" in
              x86_64)
                echo ARCH=amd64
                ;;
              aarch64)
                echo ARCH=arm64
                ;;
            esac
          ) | tee -a ${GITHUB_OUTPUT}
      
      - name: Run tests
        run: |
          make -C ${{ env.CLONE_DIR }} test-release
        env:
          DEBUG: ${{ runner.debug }}
          LOCAL_TESTER_IMAGE: ${{ needs.config.outputs.LOCAL_TESTER_IMAGE }}
          LOCAL_TESTER_RESULTS: ${{ needs.config.outputs.LOCAL_TESTER_RESULTS }}
          TEST_DATE: ${{ needs.config.outputs.TEST_DATE }}
          TEST_ID: ${{ needs.config.outputs.TEST_ID }}__${{ steps.arch.outputs.ARCH }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ needs.config.outputs.TEST_ARTIFACT }}__${{ steps.arch.outputs.ARCH }}
          path: ${{ env.CLONE_DIR }}/${{ needs.config.outputs.LOCAL_TESTER_RESULTS }}/**

  push:
    needs:
      - config
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true
      
      - name: Clone release tracker
        uses: mentalsmash/actions/release-tracker/checkout@master
        with:
          repository: ${{ needs.config.outputs.TRACKER_REPO }}
          user-name: ${{ needs.config.outputs.TRACKER_USER_NAME }}
          user-email: ${{ needs.config.outputs.TRACKER_USER_EMAIL }}
          token: ${{ secrets.RELEASE_TRACKER_REPO_PAT }}

      - name: Build image
        uses: mentalsmash/actions/docker/builder@master
        with:
          base-image: ${{ needs.config.outputs.PRERELEASE_IMAGE }}
          build-platforms: ${{ needs.config.outputs.DOCKER_BUILD_PLATFORMS }}
          dockerfile: ${{ env.CLONE_DIR }}/docker/release/Dockerfile
          context: ${{ env.CLONE_DIR }}
          image-repos: ${{ needs.config.outputs.RELEASE_REPOS }}
          image-flavor-config: ${{ needs.config.outputs.DOCKER_FLAVOR_CONFIG }}
          image-tags-config: ${{ needs.config.outputs.DOCKER_TAGS_CONFIG }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-user: ${{ github.actor }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          action: push
  
      - name: Create and push release tracker entry
        uses: mentalsmash/actions/release-tracker/add-docker@master
        with:
          repository: ${{ needs.config.outputs.TRACKER_REPO }}
          track: ${{ needs.config.outputs.BUILD_PROFILE }}
          version: ${{ needs.config.outputs.BUILD_VERSION }}
          images: ${{ needs.config.outputs.RELEASE_FINAL_IMAGES }}
