name: Release (Log to Tracker)
run-name: |
  release (log) [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  workflow_call:

concurrency:
  group: release-tracker
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

env:
  CLONE_DIR: src/repo

jobs:
  add-entry:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}
          submodules: true

      - name: Load configuration
        uses: mentalsmash/actions/pyconfig/configuration@master
        with:
          clone-dir: ${{ env.CLONE_DIR }}

      - name: Configure workflow
        id: config
        run: |
          (
            printf -- "BUILD_PROFILE=%s\n" "$(jq '.build.profile' -r pyconfig.json)"
            printf -- "BUILD_VERSION=%s\n" "$(jq '.build.version' -r pyconfig.json)"
            printf -- "BUILD_DATE=%s\n" "$(jq '.build.date' -r pyconfig.json)"
            printf -- "GH_ORG=%s\n" "$(jq '.release.gh.org' -r pyconfig.json)"
            printf -- "GH_PACKAGE=%s\n" "$(jq '.release.gh.package' -r pyconfig.json)"
            printf -- "TRACKER_USER_NAME=%s\n" "$(jq '.release.tracker.user.name' -r pyconfig.json)"
            printf -- "TRACKER_USER_EMAIL=%s\n" "$(jq '.release.tracker.user.email' -r pyconfig.json)"
            printf -- "TRACKER_REPO=%s\n" "$(jq '.release.tracker.repository' -r pyconfig.json)"
            echo "RELEASE_FINAL_IMAGES<<EOF"
            # printf -- "%s\n" "$(jq '.release.final_images_config' -r pyconfig.json)"
            jq '.release.final_images_config' -r pyconfig.json
            echo
            echo EOF
          ) | tee -a ${GITHUB_OUTPUT}
      
      - name: Clone release tracker
        uses: mentalsmash/actions/release-tracker/checkout@master
        if: steps.config.outputs.GH_PACKAGE
        with:
          repository: ${{ steps.config.outputs.TRACKER_REPO }}
          user-name: ${{ steps.config.outputs.TRACKER_USER_NAME }}
          user-email: ${{ steps.config.outputs.TRACKER_USER_EMAIL }}
          token: ${{ secrets.RELEASE_TRACKER_REPO_PAT }}

      - name: Create and push release tracker entry
        uses: mentalsmash/actions/release-tracker/add-docker@master
        if: steps.config.outputs.GH_PACKAGE
        with:
          repository: ${{ steps.config.outputs.TRACKER_REPO }}
          track: ${{ steps.config.outputs.BUILD_PROFILE }}
          version: ${{ steps.config.outputs.BUILD_VERSION }}
          images: ${{ steps.config.outputs.RELEASE_FINAL_IMAGES }}

      - name: Read commit hash
        run: |
          echo TRACKER_COMMIT=$(cd src/tracker && git rev-parse --short HEAD) >> release-tracker.commit
      
      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-tracker-${{ steps.config.outputs.BUILD_DATE }}
          path: release-tracker*
        if: always()
