name: Release
run-name: |
  release [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  actions:  write
  contents: write
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/release_docker.yml
    secrets: inherit
  
  deb:
    uses: ./.github/workflows/release_deb.yml
    secrets: inherit
  
  push:
    needs:
      - docker
      - deb
    uses: ./.github/workflows/release_push.yml
    secrets: inherit
