name: Release Tracker (Initialize)
run-name: release tracker [initialize]

on:
  workflow_dispatch:

concurrency:
  group: reltracker-init
  cancel-in-progress: false

permissions:
  contents: read

env:
  CLONE_DIR: src/repo
  TRACKER_DIR: src/tracker

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CLONE_DIR }}

      - name: Load configuration
        uses: mentalsmash/actions/pyconfig/configuration@master
        with:
          clone-dir: ${{ env.CLONE_DIR }}
  
      - name: Configure workflow
        id: config
        run: |
          (
            echo TRACKER_USER_NAME=$(jq '.release.tracker.user.name' -r pyconfig.json)
            echo TRACKER_USER_EMAIL=$(jq '.release.tracker.user.email' -r pyconfig.json)
            echo TRACKER_REPO=$(jq '.release.tracker.repository' -r pyconfig.json)
          ) | tee -a ${GITHUB_OUTPUT}

      - name: Initialize release tracker
        uses: mentalsmash/actions/release-tracker/initialize@master
        with:
          tracks-dir: ${{ env.TRACKER_DIR }}/releases
          repository: ${{ steps.config.outputs.TRACKER_REPO }}
          repository-dir: ${{ env.TRACKER_DIR }}
          repository-user-name: ${{ steps.config.outputs.TRACKER_USER_NAME }}
          repository-user-email: ${{ steps.config.outputs.TRACKER_USER_EMAIL }}
          repository-token: ${{ secrets.RELEASE_TRACKER_REPO_PAT }}
