name: Release
run-name: |
  release [${{github.ref_type == 'tag' && 'stable' || 'nightly' }}, ${{github.ref_name}}]

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

env:
  CLONE_DIR: src/repo

jobs:
  build:
    uses: ./.github/workflows/_release_build.yml
    secrets: inherit

  test:
    needs:
      - build
    uses: ./.github/workflows/_release_test.yml
    secrets: inherit

  push:
    needs:
      - test
    uses: ./.github/workflows/_release_push.yml
    secrets: inherit

  update_badges:
    needs:
      - push
    uses: ./.github/workflows/_release_badges.yml
    secrets: inherit

  deb_release:
    needs:
      - test
    uses: ./.github/workflows/deb_release.yml
    secrets: inherit

    